name: Build

on:
  workflow_call:
  workflow_dispatch:

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  test:
    uses: ./.github/workflows/test.yml
    permissions:
      contents: read

  build:
    name: Build distribution
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set package version from git
        run: |
          VERSION=$(git describe --tags --always)
          printf '__version__ = "%s"  # Set by CI from git describe.\n' "$VERSION" > ariadne_lambda/__about__.py

      - name: Build package
        run: uv build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  sign-release:
    name: Sign Python distribution with Sigstore
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Download distribution artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Sign distributions with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl

      - name: Store signed distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
          overwrite: true
