name: Run Tests

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: Build the package
        run: |
          hatch build

      - name: Run tests
        run: |
          hatch run test
